export default {
  start: 'loadStart',
  todo: 'loadTodo',
  saga: 'SAGA',
  login: 'LOGIN',
  logout: 'LOGOUT',
  dressForNewLook: 'DRESS_FOR_NEW_LOOK',
  getUserTest: 'GET_USER_TEST',
  getUserTestSaga: 'GET_USER_TEST_SAGA',
  deleteLook: 'DELETE_LOOK_SAGA',
  addTag: 'ADD_TAG',
  deleteTag: 'DELETE_TAG',
  onChangeName: 'ON_CHANGE_NAME',
  clearDressForNewLook: 'CLEAR_DRESS_FOR_NEW_LOOK',
  watcherDeleteLook: 'watcherDeleteLook',
  head: 'head',
  body: 'body',
  legs: 'legs',
  feet: 'feet',
  arrImg: 'arrImg',
  lookis: 'lookis',
};
