export default {
  start: 'loadStart',
  todo: 'loadTodo',
  saga: 'SAGA',
  login: 'LOGIN',
  logout: 'LOGOUT',
  dressForNewLook: 'DRESS_FOR_NEW_LOOK',
  getUserTest: 'GET_USER_TEST',
  getUserTestSaga: 'GET_USER_TEST_SAGA',
  deleteLookSaga: 'DELETE_LOOK_SAGA',
  headUrl: 'addUrlHead',
  bodyUrl: 'addUrlBody',
  legsUrl: 'addUrlLegs',
  lapkiUrl: 'addUrlLapki',
  arrImg: 'arrImg',
};
